version: '3.8'
services:
  movies:
    image: madhavi309/paytmrepo:movies
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: madhavi309/paytmrepo:train
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: madhavi309/paytmrepo:dth
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: madhavi309/paytmrepo:recharge
    ports:
      - "84:80"
    deploy:
      replicas: 3

