version: '3.8'
services:
  movies:
    image: madhavi309/paytmrepo:movies
    ports:
      - "86:80"
    deploy:
      replicas: 3
  train:
    image: madhavi309/paytmrepo:train
    ports:
      - "87:80"
    deploy:
      replicas: 3
  dth:
    image: madhavi309/paytmrepo:dth
    ports:
      - "88:80"
    deploy:
      replicas: 3
  recharge:
    image: madhavi309/paytmrepo:recharge
    ports:
      - "89:80"
    deploy:
      replicas: 3

